### ISSUE TITLE
denormalizr?

### ISSUE THREAD

**Issue by tlrobinson** [gaearon/normalizr#17] opened 2015-08-18 06:29 UTC
(I'm new to redux/normalizr so tell me if I'm totally off-base)

It's often more convenient to pass nested objects down as props, so I find myself writing selectors like so:

```
    return {
        foo: {
            ...foo,
            bars: foo.bars.map(id => state.bars[id])
        }
    };
```

Am I doing it wrong, or would it be nice to have a `denormalizr` that converts the normalized objects back to nested objects (perhaps using the same schema definition?)

**Comment by dotcs** [comment] 2015-08-22 11:49
I am working on this. As suggested it is entirely possible to use the same schema definition to convert back to nested objects. I will add a PR within the next days to see what you guys think about it. Stay tuned.

**Comment by gaearon** [comment] 2015-08-24 13:47
Closing, as this is duplicate of https://github.com/gaearon/normalizr/issues/1.
See also the discussion there.

**Closed by gaearon** 2015-08-24 13:47 UTC
